# Generated by Django 2.1.4 on 2018-12-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=250)),
                ('sauthor', models.CharField(max_length=250)),
                ('nprice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ncnt', models.DecimalField(decimal_places=0, max_digits=6)),
                ('sshortdescr', models.TextField()),
                ('sfulldescr', models.TextField()),
                ('sagerestrict', models.CharField(max_length=3)),
                ('sisbn', models.CharField(max_length=30)),
                ('npagecnt', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
    ]
