# Generated by Django 2.1.4 on 2018-12-23 19:23

from django.db import migrations, models
import django.db.models.deletion
import products.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181223_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=products.utils.get_default_category, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
    ]
